### ISSUE TITLE
Installation without CocoaPods?

### ISSUE THREAD

**Issue by dfmuir** [davbeck/TUSafariActivity#17]
Hello,

Is it possible to install TUSafariActivity without using CocoaPods? When I add all of the files and try to use it, I get the error:

2015-05-10 01:42:48.363 QuiltingTutorials[33414:4351195] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* -[NSBundle initWithURL:]: nil URL argument'

**Comment by Jman012** [comment]
I'm getting the same issue here. It seems to do with the activityTitle method, and getting the localized strings.

**Comment by davbeck** [comment]
Using this library without Cocoapods isn't specifically supported, but you should be able to get it to work by creating a TUSafariActivity.bundle with the assets and adding that to your project.

But really, you should just use Cocoapods. It's awesome.

**Comment by fel1x-developer** [comment]
I can replace it with SPM, but the name of the project should be changed for that. I personally prefer SPM over Cocoapods since SPM doesn't require any CLI works. Furthermore, there are some problems related to Cocoapods installation on macOS. ([See here](https://stackoverflow.com/questions/53135863/macos-mojave-ruby-config-h-file-not-found)) Because Apple does not update ruby on macOS (it stays on 2.6), each person needs to install homebrew and then install ruby again. This is too much work. On the other hand, SPM is simpler and faster to setup.

**Comment by davbeck** [comment]
SPM didn't exist in 2015.

**Comment by davbeck** [comment]
You can now use both SPM and Carthage as of [1.0.5](https://github.com/davbeck/TUSafariActivity/releases/tag/1.0.5).
